/*
 * This file was generated by the Gradle 'init' task.
 */
rootProject.name = "kodel"

include("kutil")
include("kodel:api")
include("kodel:coroutine")
include("kodel:core")
@DslMarker
annotation class IncludeDslMarker

@IncludeDslMarker
class IncludeDsl(
    private val prefix: List<String>,
    private val settings: Settings,
) {
    fun includeIfExists(vararg name: String): Boolean = if (
        file(path(name).joinToString(separator = "/")).exists()
    ) {
        include(*name)
        true
    } else false


    fun include(vararg name: String) = settings.include(path(name).joinToString(separator = ":"))

    private fun path(name: Array<out String>) = (prefix + name).let { pathName ->
        var name: String? = null
        pathName.map {
            name = if (name == null) it
            else "$name-$it"
            name
        }
    }

    fun group(name: String, block: IncludeDsl.() -> Unit) = IncludeDsl(prefix + name, settings).block()
    fun includeIfExistsAndGroup(name: String, block: IncludeDsl.() -> Unit) =
        if (includeIfExists(name)) group(name, block)
        else Unit
}

fun Settings.includeDsl(block: IncludeDsl.() -> Unit) {
    IncludeDsl(emptyList(), this).block()
}
includeDsl {
    group("kodel") {
        includeIfExists("domain")
    }
}