/*
 * This file was generated by the Gradle 'init' task.
 */
import dependencies.ProjectConfig
import org.jetbrains.kotlin.gradle.tasks.KotlinCompilationTask

plugins {
    kotlin("multiplatform")
    kotlin("plugin.serialization")
}

val kotlinVersion = "2.3.10"

repositories {
    mavenLocal()
    mavenCentral()

    maven {
        url = uri("https://maven.pkg.jetbrains.space/public/p/kotlinx-html/maven")
    }
}

dependencies {
    commonMainImplementation("org.jetbrains.kotlin:kotlin-reflect:$kotlinVersion")
    commonTestImplementation(kotlin("test-common"))
    commonMainImplementation("org.jetbrains.kotlinx:kotlinx-serialization-core:1.7.3")
    commonMainImplementation("io.ktor:ktor-http:3.0.2")
    commonMainImplementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.2")
}

version = ProjectConfig.VERSION
group = ProjectConfig.GROUP


kotlin {
    jvmToolchain(25)
    jvm("jvm") {
    }
//  js {
//    browser {}
//    nodejs { }
//  }

    sourceSets {
        jvmMain {
            dependencies {
                implementation(kotlin("test-junit5"))
            }

        }
        jvmTest {
            dependencies {
                implementation(kotlin("test-junit5"))
            }
        }
        commonMain {
            dependencies {
                implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.2")
            }
        }
        commonTest {}
    }
}



tasks {
    withType<KotlinCompilationTask<*>> {
        compilerOptions {
            freeCompilerArgs.add("-Xexpect-actual-classes")
            if (name.contains("Js", ignoreCase = true)) {
                freeCompilerArgs.add("-Xexpect-actual-classes")
            }
        }
    }

    withType<Test> {
        useJUnitPlatform()
    }

}