/*
 * This file was generated by the Gradle 'init' task.
 */
import dependencies.ProjectConfig
import org.jetbrains.kotlin.gradle.tasks.KotlinCompilationTask

plugins {
  kotlin("multiplatform")
}

repositories {
  mavenLocal()
  mavenCentral()

  maven {
    url = uri("https://maven.pkg.jetbrains.space/public/p/kotlinx-html/maven")
  }
}

dependencies {
  commonMainImplementation("org.jetbrains.kotlin:kotlin-stdlib")
  commonMainImplementation("org.jetbrains.kotlin:kotlin-reflect")
  commonTestImplementation(kotlin("test-common"))
//  commonMainImplementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3")
}

version = ProjectConfig.VERSION
group = ProjectConfig.GROUP


kotlin {
  jvmToolchain(25)
  jvm("jvm") {
  }
  js(IR) {
    browser {}
    nodejs { }
  }

  sourceSets {
    val jvmMain by getting {
      dependencies {
        implementation(kotlin("test-junit5"))
      }

    }
    val jvmTest by getting
    val commonMain by getting {
      dependencies {
        implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3")
      }
    }
    val commonTest by getting
  }
}



tasks {
  withType<KotlinCompilationTask<*>> {
    compilerOptions {
      freeCompilerArgs.add("-Xexpect-actual-classes")
    }
  }

}